package telas;

import data.Filmes;
import data.FilmesDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author John
 */
public class CenaflixInicio extends javax.swing.JFrame {

    /**
     * Creates new form telaCenaflix
     */
    public CenaflixInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneDesktop = new javax.swing.JDesktopPane();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        boxCategoria = new javax.swing.JComboBox<>();
        btnRelatorio = new javax.swing.JButton();
        txtIdPesquisa = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblConfirmacao = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaneDesktop.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 102)));

        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 51, 51));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pipoca redimensionada1.png"))); // NOI18N
        lblTitulo.setText("Cenaflix");

        lblNome.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome do Filme:");

        lblData.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data de Lançamento:");

        lblCategoria.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoria:");

        btnCadastrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Clique para cadastrar o filme");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        btnEditar.setText("Atualizar");
        btnEditar.setToolTipText("Clique para atualizar os dados");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtNome.setToolTipText("Digite o nome do filme");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtData.setToolTipText("Digite a data de lançamento");

        boxCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acão", "Terror", "Comédia", "Drama", "Ficção", "Fantasia", "Suspense", "Religioso", "Romance", "Super Herói", " " }));
        boxCategoria.setToolTipText("Esolha a categoria do filme");

        btnRelatorio.setFont(btnCadastrar.getFont());
        btnRelatorio.setText("Relatório de Filmes");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        txtIdPesquisa.setToolTipText("Digite o ID");
        txtIdPesquisa.setCaretColor(new java.awt.Color(0, 0, 0));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(lblNome.getFont());
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");

        txtId.setEnabled(false);

        lblConfirmacao.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        lblConfirmacao.setForeground(new java.awt.Color(51, 255, 51));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        PaneDesktop.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(lblNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(lblData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(lblCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(txtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(txtData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(boxCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(btnRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(txtIdPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(btnConsultar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(txtId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(lblConfirmacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PaneDesktop.setLayer(btnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PaneDesktopLayout = new javax.swing.GroupLayout(PaneDesktop);
        PaneDesktop.setLayout(PaneDesktopLayout);
        PaneDesktopLayout.setHorizontalGroup(
            PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneDesktopLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorio)
                        .addGap(49, 49, 49))
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(186, 186, 186)
                        .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaneDesktopLayout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(PaneDesktopLayout.createSequentialGroup()
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneDesktopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneDesktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        PaneDesktopLayout.setVerticalGroup(
            PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneDesktopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneDesktopLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(lblData)))
                .addGap(18, 18, 18)
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addGap(42, 42, 42)
                .addComponent(lblConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaneDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneDesktop)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (!emptyFields2()) {
            try {
                String nome = txtNome.getText();
                String data = txtData.getText();
                String categoria = boxCategoria.getSelectedItem().toString();
                int id = Integer.parseInt(txtId.getText());

                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date Data = formato.parse(data);
                Filmes filme = new Filmes();
                filme.setNome(nome);
                filme.setData(Data);
                filme.setCategoria(categoria);
                filme.setId(id);

                FilmesDao filmes = new FilmesDao();

                filmes.editarFilme(filme);

                txtId.setText("");
                txtNome.setText("");
                txtData.setText("");
                boxCategoria.setSelectedIndex(0);
            } catch (ParseException ex) {
                System.out.println("Erro de conversão " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if (!emptyFields()) {
            if (!validarCampo()) {

                try {
                    String nomeFilme = txtNome.getText();
                    String categoria = boxCategoria.getSelectedItem().toString();
                    String dataLanc = txtData.getText();
                    Filmes filme = new Filmes();

                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

                    filme.setNome(nomeFilme);
                    filme.setData(formato.parse(dataLanc));
                    filme.setCategoria(categoria);

                    FilmesDao filmeDao = new FilmesDao();
                    filmeDao.salvarFilmes(filme);

                    txtNome.setText("");
                    txtData.setText("");
                    boxCategoria.setSelectedIndex(0);

                } catch (ParseException ex) {
                    System.out.println("Erro de conversão: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        CenaflixRelatorio relatorio = new CenaflixRelatorio();
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (!idVazio()) {
            int idPesquisa = Integer.parseInt(txtIdPesquisa.getText());

            FilmesDao filmesDAO = new FilmesDao();
            Filmes filme = filmesDAO.consultarFilme(idPesquisa);

            if (filme == null) {
                JOptionPane.showMessageDialog(this, "Filme não encontrado!");
            } else {
                txtId.setText(String.valueOf(filme.getId()));
                txtNome.setText(filme.getNome());
                txtData.setText(filme.getData().toString());
                boxCategoria.setSelectedItem(filme.getCategoria());

            }
            txtIdPesquisa.setText("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtId.setText("");
        txtNome.setText("");
        txtData.setText("");
        boxCategoria.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CenaflixInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CenaflixInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CenaflixInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CenaflixInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CenaflixInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PaneDesktop;
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblConfirmacao;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPesquisa;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para validar campo de data ao inserir
     */
    private boolean validarCampo() {
        boolean validado = true;

        boolean dataValida = txtData.getText().matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}");

        if (dataValida == false) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! A data tem que ser no formato: 04/02/1993");
            txtData.requestFocus();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Dados incluidos com sucesso");
            validado = false;
        }

        return validado;
    }

    /**
     * Método para verificar se os campos não estão vazios
     */
    private boolean emptyFields() {

        boolean vazio = true;

        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Nome não pode ser vazio.");
            txtNome.requestFocus();

        } else if (txtData.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Data não pode ser vazio.");
            txtData.requestFocus();

        } else {
            vazio = false;
        }
        return vazio;
    }

    /**
     * Método para verificar se id de consulta não esta vazio (exibe mensagem
     * diferente)
     */
    private boolean idVazio() {
        boolean vazio = true;

        if (txtIdPesquisa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Digite um ID válido para retornar a consulta");
            txtIdPesquisa.requestFocus();

        } else {
            vazio = false;
        }
        return vazio;
    }

    /**
     * Método para instruir usuário á fazer uma consulta antes de editar algum
     * dado
     */
    private boolean emptyFields2() {

        boolean vazio = true;

        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Faça uma consulta para trazer os dados para atualizar");
            txtIdPesquisa.requestFocus();

        } else {
            vazio = false;
        }
        return vazio;
    }

    /**
     * Tela inicio com alguns métodos criados
     *
     * @author Jhon
     * @version 1.0
     * @since Primeira versão
     */
}
